# This is a basic workflow to help you get started with Actions

name: reploy to myself server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Disable Openssl New features
        run: set NODE_OPTIONS=-openssl-legacy-provider
      
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn install
      
      - name: Build
        run: yarn docs:build

      # deploy server
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: '${{ secrets.SERVER_USER_NAME }}'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          port: ${{ secrets.SERVER_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './docs-dist/*'  # 对应我们项目build的文件夹路径
          remote_path: '/www/wwwroot/wangez.cn/'
      # deploy static file to server
      - name: deploy static file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: '${{ secrets.SERVER_USER_NAME }}'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          port: ${{ secrets.SERVER_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './docs-dist/umi.*'  # 对应我们项目build的文件夹路径
          remote_path: '/www/wwwroot/static'
